# Generated by Django 5.2.12 on 2026-03-11 09:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=64, unique=True, verbose_name="Сезон"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
            ],
            options={
                "verbose_name": "Сезон",
                "verbose_name_plural": "Сезоны",
                "ordering": ["-is_active", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, default="", max_length=16, verbose_name="Коротко"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="Город"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="team_logos/",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
            ],
            options={
                "verbose_name": "Команда",
                "verbose_name_plural": "Команды",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Начало"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Запланирован"),
                            ("live", "В лайве"),
                            ("finished", "Завершён"),
                        ],
                        default="scheduled",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "venue",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="Арена"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="games",
                        to="league.season",
                        verbose_name="Сезон",
                    ),
                ),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="away_games",
                        to="league.team",
                        verbose_name="Гости",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_games",
                        to="league.team",
                        verbose_name="Хозяева",
                    ),
                ),
            ],
            options={
                "verbose_name": "Матч",
                "verbose_name_plural": "Матчи",
                "ordering": ["-start_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=60, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=60, verbose_name="Фамилия")),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99),
                        ],
                        verbose_name="Номер",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="Позиция"
                    ),
                ),
                (
                    "height_cm",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Рост (см)"
                    ),
                ),
                (
                    "weight_kg",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Вес (кг)"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "search_name",
                    models.CharField(
                        db_index=True, default="", editable=False, max_length=200
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="players",
                        to="league.team",
                        verbose_name="Команда",
                    ),
                ),
            ],
            options={
                "verbose_name": "Игрок",
                "verbose_name_plural": "Игроки",
                "ordering": ["last_name", "first_name", "id"],
            },
        ),
        migrations.CreateModel(
            name="GameRoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_starter",
                    models.BooleanField(default=False, verbose_name="В старте"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="В заявке"),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rosters",
                        to="league.game",
                        verbose_name="Матч",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rosters",
                        to="league.player",
                        verbose_name="Игрок",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rosters",
                        to="league.team",
                        verbose_name="Команда",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на матч",
                "verbose_name_plural": "Заявки на матч",
            },
        ),
        migrations.AddConstraint(
            model_name="player",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number__isnull", False)),
                fields=("team", "number"),
                name="uniq_team_number_when_present",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameroster",
            constraint=models.UniqueConstraint(
                fields=("game", "player"), name="uniq_game_player"
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                condition=models.Q(("home_team", models.F("away_team")), _negated=True),
                name="home_team_not_away_team",
            ),
        ),
    ]
