# Generated by Django 5.2.12 on 2026-03-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0002_remove_gameroster_roster_team_matches_player_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="player_photos/", verbose_name="Фото"
            ),
        ),
    ]
