# Generated by Django 5.2.12 on 2026-03-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0003_player_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="clock_running",
            field=models.BooleanField(default=False, verbose_name="Часы идут"),
        ),
        migrations.AddField(
            model_name="game",
            name="clock_seconds",
            field=models.PositiveSmallIntegerField(
                default=600, verbose_name="Секунды на табло"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="current_period",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Текущий период"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="period_duration",
            field=models.PositiveSmallIntegerField(
                default=600, verbose_name="Длительность периода (сек.)"
            ),
        ),
    ]
