# Generated by Django 5.2.12 on 2026-03-11 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0004_game_clock_running_game_clock_seconds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="clock_updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Время обновления часов"
            ),
        ),
    ]
