# Generated by Django 5.2.12 on 2026-03-11 09:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("league", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("fg2_made", "2 очка — попадание"),
                            ("fg2_miss", "2 очка — промах"),
                            ("ft_made", "Штрафной — попадание"),
                            ("ft_miss", "Штрафной — промах"),
                            ("assist", "Передача (ассист)"),
                            ("reb_o", "Подбор в нападении"),
                            ("reb_d", "Подбор в защите"),
                            ("steal", "Перехват"),
                            ("turnover", "Потеря"),
                            ("block", "Блок-шот"),
                            ("foul", "Фол игрока"),
                            ("foul_drawn", "Фол соперника (на игроке)"),
                        ],
                        max_length=20,
                        verbose_name="Событие",
                    ),
                ),
                (
                    "period",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Период",
                    ),
                ),
                (
                    "clock_seconds",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(900),
                        ],
                        verbose_name="Секунд на таймере",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Примечание",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="league.game",
                        verbose_name="Матч",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="league.player",
                        verbose_name="Игрок",
                    ),
                ),
                (
                    "related_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="related_events",
                        to="league.player",
                        verbose_name="Связанный игрок",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="league.team",
                        verbose_name="Команда",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие матча",
                "verbose_name_plural": "События матча",
                "ordering": ["game_id", "period", "-clock_seconds", "sequence", "id"],
                "indexes": [
                    models.Index(
                        fields=["game", "period", "clock_seconds", "sequence"],
                        name="live_gameev_game_id_648411_idx",
                    ),
                    models.Index(
                        fields=["game", "team"], name="live_gameev_game_id_aa14c9_idx"
                    ),
                    models.Index(
                        fields=["game", "player"], name="live_gameev_game_id_ded2be_idx"
                    ),
                ],
                "constraints": [],
            },
        ),
        migrations.CreateModel(
            name="PlayerGameStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.PositiveIntegerField(default=0, verbose_name="Очки")),
                (
                    "assists",
                    models.PositiveIntegerField(default=0, verbose_name="Передачи"),
                ),
                (
                    "rebounds_off",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Подборы (нап.)"
                    ),
                ),
                (
                    "rebounds_def",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Подборы (защ.)"
                    ),
                ),
                (
                    "steals",
                    models.PositiveIntegerField(default=0, verbose_name="Перехваты"),
                ),
                (
                    "turnovers",
                    models.PositiveIntegerField(default=0, verbose_name="Потери"),
                ),
                (
                    "blocks",
                    models.PositiveIntegerField(default=0, verbose_name="Блок-шоты"),
                ),
                (
                    "fouls",
                    models.PositiveIntegerField(default=0, verbose_name="Фолы игрока"),
                ),
                (
                    "fouls_against",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Фолы соперника"
                    ),
                ),
                (
                    "shots_att",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Броски: попытки"
                    ),
                ),
                (
                    "shots_made",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Броски: попадания"
                    ),
                ),
                (
                    "fg2_att",
                    models.PositiveIntegerField(
                        default=0, verbose_name="2 очка: попытки"
                    ),
                ),
                (
                    "fg2_made",
                    models.PositiveIntegerField(
                        default=0, verbose_name="2 очка: попадания"
                    ),
                ),
                (
                    "ft_att",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Штрафные: попытки"
                    ),
                ),
                (
                    "ft_made",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Штрафные: попадания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_stats",
                        to="league.game",
                        verbose_name="Матч",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="game_stats",
                        to="league.player",
                        verbose_name="Игрок",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="player_stats",
                        to="league.team",
                        verbose_name="Команда",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика игрока (матч)",
                "verbose_name_plural": "Статистика игроков (матч)",
                "indexes": [
                    models.Index(
                        fields=["game", "team"], name="live_player_game_id_ec3229_idx"
                    ),
                    models.Index(
                        fields=["game", "player"], name="live_player_game_id_a3c575_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("game", "player"), name="uniq_game_player_stat"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TeamGameStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.PositiveIntegerField(default=0, verbose_name="Очки")),
                (
                    "assists",
                    models.PositiveIntegerField(default=0, verbose_name="Передачи"),
                ),
                (
                    "rebounds_off",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Подборы (нап.)"
                    ),
                ),
                (
                    "rebounds_def",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Подборы (защ.)"
                    ),
                ),
                (
                    "steals",
                    models.PositiveIntegerField(default=0, verbose_name="Перехваты"),
                ),
                (
                    "turnovers",
                    models.PositiveIntegerField(default=0, verbose_name="Потери"),
                ),
                (
                    "blocks",
                    models.PositiveIntegerField(default=0, verbose_name="Блок-шоты"),
                ),
                (
                    "fouls",
                    models.PositiveIntegerField(default=0, verbose_name="Фолы игрока"),
                ),
                (
                    "fouls_against",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Фолы соперника"
                    ),
                ),
                (
                    "shots_att",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Броски: попытки"
                    ),
                ),
                (
                    "shots_made",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Броски: попадания"
                    ),
                ),
                (
                    "fg2_att",
                    models.PositiveIntegerField(
                        default=0, verbose_name="2 очка: попытки"
                    ),
                ),
                (
                    "fg2_made",
                    models.PositiveIntegerField(
                        default=0, verbose_name="2 очка: попадания"
                    ),
                ),
                (
                    "ft_att",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Штрафные: попытки"
                    ),
                ),
                (
                    "ft_made",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Штрафные: попадания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_stats",
                        to="league.game",
                        verbose_name="Матч",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="team_stats",
                        to="league.team",
                        verbose_name="Команда",
                    ),
                ),
            ],
            options={
                "verbose_name": "Командная статистика (матч)",
                "verbose_name_plural": "Командная статистика (матч)",
                "indexes": [
                    models.Index(
                        fields=["game", "team"], name="live_teamga_game_id_6c3e19_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("game", "team"), name="uniq_game_team_stat"
                    )
                ],
            },
        ),
    ]
