# Generated by Django 5.2.12 on 2026-03-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("live", "0001_initial"),
    ]

    operations = []
